### ISSUE TITLE
Test failures are not very informative

### ISSUE THREAD

**Issue by ch1c0t** [patriciomacadden/hobbit#21]
I commented out some code and, after running `bundle exec rake test`, got the test failures of this kind:
```
error: 1 != 
file: /usr/lib/ruby/2.2.0/rake/rake_test_loader.rb
line: 10

error: hobbit != 
file: /usr/lib/ruby/2.2.0/rake/rake_test_loader.rb
line: 10

error: 1 != 
file: /usr/lib/ruby/2.2.0/rake/rake_test_loader.rb
line: 10

error: hobbit != 
file: /usr/lib/ruby/2.2.0/rake/rake_test_loader.rb
line: 10

error: 1 != 
file: /usr/lib/ruby/2.2.0/rake/rake_test_loader.rb
line: 10

error: hobbit != 
file: /usr/lib/ruby/2.2.0/rake/rake_test_loader.rb
line: 10
```

**Comment by patriciomacadden** [comment]
You are right. I don't think this could be fixed in hobbit. You'll have to take a look at oktobertest. In the meantime you could just run the tests one by one.

**Comment by ch1c0t** [comment]
>You'll have to take a look at oktobertest.

I just throught that you, as a person who authored [oktobertest](https://github.com/patriciomacadden/oktobertes), are in a better position to fix it properly.

>In the meantime you could just run the tests one by one.

That option is really far away from my expectations about ideal testing environment.
